<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Reset</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FunctionCallEventArgs.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FunctionCallEventArgs.cs" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.30.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SKLIb\SKLIb.csproj" />
	</ItemGroup>

</Project>
