using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InquiryLib;

public class Agreement
{
    /// <summary>
    /// Gets or sets the enrollment identifier
    /// </summary>
    public string EnrollmentId { get; set; }

    /// <summary>
    /// Gets or sets the client name
    /// </summary>
    public string ClientName { get; set; }

    /// <summary>
    /// Gets or sets the date when the agreement was signed
    /// </summary>
    public DateTime SignedDate { get; set; }

    /// <summary>
    /// Gets or sets the expiration date of the agreement
    /// </summary>
    public DateTime ExpirationDate { get; set; }

    public string Status { get; set; }
}

// Generated by Copilot
// [TIMESTAMP_FROM_STEP_1] | 4 properties added | Added EnrollmentId, ClientName, SignedDate, and ExpirationDate properties with XML documentation | Time Taken 1 min
